@OutboxPlayground.Samples.EFSqlServerSample_HostAddress = http://localhost:5284

GET {{OutboxPlayground.Samples.EFSqlServerSample_HostAddress}}/
Accept: application/json

###

POST {{OutboxPlayground.Samples.EFSqlServerSample_HostAddress}}/
Content-Type: application/json
sessionId: {{$guid}}
deviceType: Mobile

{
  "id": "{{$guid}}",
  "userId": "{{$guid}}",
  "userName": "test-user",
  "amount": 99.99,
  "currency": "USD",
  "paymentMethod": "CreditCard",
  "customerId": "{{$guid}}",
  "createdAt": "{{$datetime iso8601}}",
  "status": 0
}

###

POST {{OutboxPlayground.Samples.EFSqlServerSample_HostAddress}}/multi
Content-Type: application/json
sessionId: {{$guid}}
deviceType: Mobile

{
  "id": "{{$guid}}",
  "userId": "{{$guid}}",
  "userName": "test-user",
  "amount": 99.99,
  "currency": "USD",
  "paymentMethod": "CreditCard",
  "customerId": "{{$guid}}",
  "createdAt": "{{$datetime iso8601}}",
  "status": 0
}




