<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.SchemaRegistry" Version="2.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutboxPlayground.Infra.Abstractions\OutboxPlayground.Infra.Abstractions.csproj" />
    <ProjectReference Include="..\OutboxPlayground.Infra.AvroHelpers\OutboxPlayground.Infra.AvroHelpers.csproj" />
  </ItemGroup>

</Project>
